name: deploy

on:
    push:
    workflow_dispatch:
    schedule:
        # Runs everyday at 8:00 AM
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        
        # permissions:
        #   contents: write
        #   pages: write       

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            # - name: Setup Hugo
            #   uses: peaceiris/actions-hugo@v2
            #   with:
            #       hugo-version: "latest"

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  # 必须把 "latest" 改为具体的旧版本号
                  hugo-version: "0.148.0" 
                  extended: true

            - name: Build Web   
              run: hugo

            - name: Deploy Web   
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }} #  PERSONAL_TOKEN
                  external_repository: Phoenix0qi/phoenix0qi.github.io # Phoenix0qi/chongqi # 
                  publish_branch: master # cf-pages
                  publish_dir: ./public
                  commit_message: ${{ github.event.head_commit.message }}
